const eliminatedTeams = [
  'Anaheim Ducks',
  'Arizona Coyotes',
  'Boston Bruins',
  'Buffalo Sabres',
  'Calgary Flames',
  'Chicago Blackhawks',
  'Columbus Blue Jackets',
  'Dallas Stars',
  'Detroit Red Wings',
  'Florida Panthers',
  'Los Angeles Kings',
  'Minnesota Wild',
  'Montreal Canadiens',
  'Nashville Predators',
  'New Jersey Devils',
  'New York Islanders',
  'Ottawa Senators',
  'Philadelphia Flyers',
  'Pittsburgh Penguins',
  'San Jose Sharks',
  'Seattle Kraken',
  'Toronto Maple Leafs',
  'Vancouver Canucks',
  'Vegas Golden Knights',
  'Washington Capitals',
  'Winnipeg Jets'
];

export default eliminatedTeams;